server:
  port: 8899
  servlet:
    context-path: /jiang_nan
spring:
  datasource:
    url: jdbc:mysql://106.13.129.20:3306/rhubard?characterEncoding=utf8&useSSL=true
    username: root
    password: Qw962453..
logging:
  config: classpath:config/log4j2-test.yml